### ISSUE TITLE
Use websockets to update data

### ISSUE THREAD

**Issue by TheDen** [staind-io/isthereafire#1]
Currently the page hangs until the `get_address` is complete, since it needs to run before the rendered webpage is returned with the values. This isn't very UX friendly—ideally we want a static page with _loading_ assets until the data is grabbed and updated.

We can do this with [flask-socketio](https://flask-socketio.readthedocs.io/en/latest/), perhaps with a `@socketio.on('connect', namespace='/foo')` so on connection the data is collected and updated on the rendered `html`. 

Insofar as threading, I'm not sure if it's necessary if it's event driven, but that's something we can grok when we're more familiar with flask-socketio

**Comment by JamesPriest** [comment]
@TheDen Any more on this? Or should we just close it.

**Comment by TheDen** [comment]
Yeah Let's close it, we have it working now 👍
